### ISSUE TITLE
City of Columbia MO Police Data

### ISSUE THREAD

**Issue by potto216** [openpolicedata/opd-data#26]
* Source Name (such as the name of a police department): City of Columbia MO Police Data
* Website URL: https://www.como.gov/police/data-reporting-forms/
* Does this source contain police data? (Yes/No):  Yes
* What types of data does the source contain? (Use of force, traffic stops, officer demographics, etc.):  Vehicle Stop Data
* Any other important details that you found?: No

**Comment by sowdm** [comment]
This data has been added
